### ISSUE TITLE
Cargo.toml in v0.1.1 has wrong version number

### ISSUE THREAD

**Issue by EmRowlands** [jvns/dnspeep#12]
```toml
[package]
name = "dnspeep"
version = "0.1.0"
authors = ["Julia Evans <julia@jvns.ca>"]
edition = "2018"
```

It says that it's still 0.1.0, rather than 0.1.1
